// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdxrwxjypqsyasunupqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeHJ3eGp5cHFzeWFzdW51cHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MDkwMjAsImV4cCI6MjA1NDI4NTAyMH0.ULExBcjgLWCpdpuwR9qiBhAChOtJFiZfsKp3K2qE4zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);